name: shop
description: Anadolu Anahtar mobile app (locksmith store app) in Turkey

publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  visibility_detector: ^0.3.2
  flutter_svg: ^2.0.9
  form_field_validator: ^1.1.0
  cached_network_image: ^3.2.0
  animations: ^2.0.11
  url_launcher: ^6.3.0
  http: ^0.13.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.0.0
  flutter_html: ^3.0.0
  flutter_slidable: ^3.0.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  webview_flutter_platform_interface: ^2.10.0
  iyzico: ^0.1.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#1BA6D6"     # or make a full-screen gradient image and use background_image
  image: assets/splash/splash.png
  android: true
  ios: true
  android_12:
    color: "#1BA6D6"
    image: assets/splash/splash.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splash/logo-white.png" # fallback for older Android & iOS
  adaptive_icon_background: "#2A72B7" # exact blue background
  adaptive_icon_foreground: "assets/splash/logo-white.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sliders/
    - assets/flags/
    - assets/logo/
    - assets/splash/
    - .env
  fonts:
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
